"""Printable documents. Each is rendered as HTML and opened in the browser,
where the user prints or saves as PDF (no printer drivers needed in the app)."""
import html
import tempfile
import webbrowser
from pathlib import Path

from . import config as C

CSS = f"""
body{{font-family:'Space Grotesk','Segoe UI',Arial,sans-serif;color:{C.NAVY};margin:32px;font-size:13px}}
.hdr{{display:flex;justify-content:space-between;border-bottom:3px solid {C.EMERALD};padding-bottom:14px}}
h1{{margin:0;font-size:22px}} h2{{margin:0;color:{C.EMERALD};font-size:26px;text-align:right}}
.muted{{color:{C.MUTED}}} table{{width:100%;border-collapse:collapse;margin-top:18px}}
th{{background:{C.NAVY};color:#fff;text-align:left;padding:7px 8px;font-size:11px;text-transform:uppercase}}
td{{padding:7px 8px;border-bottom:1px solid {C.LINE}}} .r{{text-align:right}}
tr.tot td{{font-weight:bold;border-top:2px solid {C.NAVY}}} tr.sec td{{background:#EEF3F7;font-weight:bold}}
.grid{{display:flex;justify-content:space-between;margin-top:18px}}
.foot{{margin-top:36px;font-size:11px;color:{C.MUTED};text-align:center}}
@media print{{body{{margin:12mm}}}}
"""



def _m(v):
    v = float(v or 0)
    return f"({abs(v):,.2f})" if v < -0.004 else f"{v:,.2f}"


def _e(s):
    return html.escape(str(s or ""))


def _open(title, body):
    doc = f"<!doctype html><html><head><meta charset='utf-8'><title>{_e(title)}</title><style>{CSS}{EXTRA_CSS}</style>" \
          f"</head><body>{body}<div class='foot'>Generated by {C.APP_NAME} v{C.VERSION} \u00b7 {C.VENDOR}</div>" \
          f"<script>window.onload=()=>setTimeout(()=>window.print(),300)</script></body></html>"
    path = Path(tempfile.gettempdir()) / f"nolima_{abs(hash(title))}.html"
    path.write_text(doc, encoding="utf-8")
    webbrowser.open(path.as_uri())
    return path


def _header(company, title, subtitle=""):
    return (f"<div class='hdr'><div><h1>{_e(company['company_name'])}</h1>"
            f"<div class='muted'>{_e(company['address'])}<br>{_e(company['phone'])} {_e(company['email'])}"
            f"{'<br>TPIN: ' + _e(company['tpin']) if company.get('tpin') else ''}</div></div>"
            f"<div><h2>{_e(title)}</h2><div class='muted' style='text-align:right'>{subtitle}</div></div></div>")


def _bank_block(co):
    """Bank and mobile money details printed on every document sent to customers."""
    rows = [("Bank", co.get("bank_name")), ("Branch", co.get("bank_branch")),
            ("Account name", co.get("bank_account_name")), ("Account number", co.get("bank_account_no")),
            ("Mobile money", co.get("mobile_money"))]
    rows = [(k, v) for k, v in rows if v]
    if not rows:
        return ""
    cells = ""
    for i in range(0, len(rows), 2):
        pair = rows[i:i + 2]
        cells += "<tr>" + "".join(f"<td class='bk'>{_e(k)}</td><td class='bv'>{_e(v)}</td>" for k, v in pair) + \
            ("<td></td><td></td>" if len(pair) == 1 else "") + "</tr>"
    return (f"<div class='bank'><div class='bt'>PAYMENT DETAILS</div>"
            f"<table class='bktab'>{cells}</table></div>")


def _lines_table(co, lines, doc):
    has_disc = any((l["discount_pct"] or 0) for l in lines)
    head = ("<tr><th>Description</th><th class='r'>Qty</th><th class='r'>Unit price</th>"
            + ("<th class='r'>Disc.</th>" if has_disc else "")
            + f"<th class='r'>VAT</th><th class='r'>Amount ({_e(co['currency'])})</th></tr>")
    body = ""
    for l in lines:
        body += (f"<tr><td>{_e(l['description'])}</td><td class='r'>{l['qty']:g}</td>"
                 f"<td class='r'>{_m(l['unit_price'])}</td>"
                 + (f"<td class='r'>{(l['discount_pct'] or 0):g}%</td>" if has_disc else "")
                 + f"<td class='r'>{l['vat_rate']:g}%</td><td class='r'>{_m(l['net'])}</td></tr>")
    span = 5 if has_disc else 4
    tot = ""
    if doc["discount"]:
        tot += f"<tr><td colspan={span} class='r muted'>Discount given</td><td class='r muted'>({_m(doc['discount'])})</td></tr>"
    tot += f"<tr><td colspan={span} class='r'>Subtotal</td><td class='r'>{_m(doc['subtotal'])}</td></tr>"
    tot += f"<tr><td colspan={span} class='r'>VAT</td><td class='r'>{_m(doc['vat'])}</td></tr>"
    if doc["levy"]:
        tot += (f"<tr><td colspan={span} class='r'>Tourism levy ({float(co['tourism_levy_rate'] or 0):g}%)</td>"
                f"<td class='r'>{_m(doc['levy'])}</td></tr>")
    tot += f"<tr class='tot'><td colspan={span} class='r'>Total</td><td class='r'>{_m(doc['total'])}</td></tr>"
    return f"<table>{head}{body}{tot}", span


EXTRA_CSS = f"""
.bank{{margin-top:22px;border:1px solid {C.LINE};border-radius:10px;padding:12px 14px;background:#F6FAF8}}
.bt{{font-size:11px;font-weight:bold;color:{C.EMERALD};letter-spacing:.5px;margin-bottom:6px}}
.bktab{{margin-top:0;width:100%}} .bktab td{{border:none;padding:3px 8px 3px 0}} .bk{{color:#5B6B7C;width:16%}} .bv{{font-weight:bold;width:34%}} .stamp{{display:inline-block;padding:3px 10px;border-radius:12px;
font-size:11px;font-weight:bold}} .paid{{background:#DCFCE7;color:#166534}} .partial{{background:#FEF3C7;color:#92400E}}
.open{{background:#E0E7FF;color:#3730A3}} .void{{background:#FEE2E2;color:#991B1B}}
"""


def print_invoice(books, inv_id):
    inv, lines, co = books.invoice(inv_id), books.invoice_lines(inv_id), books.company()
    sale = inv["kind"] == "sale"
    title = "TAX INVOICE" if sale else "SUPPLIER BILL"
    if inv["status"] == "paid" and sale and inv["date"] == inv["due_date"]:
        title = "CASH SALE RECEIPT"
    status = {"paid": "PAID", "partial": "PART PAID", "open": "UNPAID", "void": "VOID"}[inv["status"]]
    table, span = _lines_table(co, lines, inv)
    body = _header(co, title, f"No. {_e(inv['number'])}<br>Date {inv['date']}<br>Due {inv['due_date']}")
    body += (f"<div class='grid'><div><b>{'Bill to' if sale else 'Supplier'}</b><br>"
             f"{_e(inv['contact'])}<br><span class='muted'>{_e(inv['address'])} {_e(inv['phone'])}</span>"
             f"{'<br>Ref: ' + _e(inv['reference']) if inv['reference'] else ''}</div>"
             f"<div><span class='stamp {inv['status']}'>{status}</span></div></div>{table}")
    if inv["amount_paid"]:
        body += f"<tr><td colspan={span} class='r'>Paid</td><td class='r'>({_m(inv['amount_paid'])})</td></tr>"
    body += (f"<tr class='tot'><td colspan={span} class='r'>Balance due</td>"
             f"<td class='r'>{_m(inv['total'] - inv['amount_paid'])}</td></tr></table>")
    pays = books.q("SELECT p.number, p.date, a.amount FROM allocations a JOIN payments p ON p.id=a.payment_id "
                   "WHERE a.invoice_id=? AND p.status<>'void' ORDER BY p.date", (inv_id,))
    if pays and inv["status"] == "partial":
        body += ("<p class='muted'>Part payments received: "
                 + "; ".join(f"{_e(p['number'])} on {p['date']}: {_m(p['amount'])}" for p in pays) + "</p>")
    if inv["memo"]:
        body += f"<p class='muted'>{_e(inv['memo'])}</p>"
    if sale:
        if inv["status"] != "paid" and co.get("payment_terms"):
            body += f"<p class='muted'>{_e(co['payment_terms'])}</p>"
        body += _bank_block(co)
    return _open(f"{title} {inv['number']}", body)


def print_quote(books, qid):
    q, lines, co = books.quote(qid), books.quote_lines(qid), books.company()
    table, span = _lines_table(co, lines, q)
    body = _header(co, "QUOTATION", f"No. {_e(q['number'])}<br>Date {q['date']}<br>Valid until {q['valid_until']}")
    body += (f"<div class='grid'><div><b>Prepared for</b><br>{_e(q['contact'])}<br>"
             f"<span class='muted'>{_e(q['address'])} {_e(q['phone'])}</span>"
             f"{'<br>Ref: ' + _e(q['reference']) if q['reference'] else ''}</div></div>{table}</table>")
    if q["memo"]:
        body += f"<p class='muted'>{_e(q['memo'])}</p>"
    body += (f"<p class='muted'>This quotation is valid until {q['valid_until']}. Prices are in {_e(co['currency'])}"
             f"{' and include VAT' if q['vat'] else ''}{' and tourism levy' if q['levy'] else ''}.</p>")
    body += _bank_block(co)
    body += "<p style='margin-top:40px'>Accepted by: ______________________ &nbsp; Date: ____________</p>"
    return _open(f"QUOTATION {q['number']}", body)


def print_payment(books, payment_id):
    p = books.one("SELECT p.*, c.name AS contact, a.name AS account FROM payments p JOIN contacts c ON "
                  "c.id=p.contact_id JOIN accounts a ON a.id=p.account_id WHERE p.id=?", (payment_id,))
    allocs = books.q("SELECT i.number, i.total, i.amount_paid, a.amount FROM allocations a JOIN invoices i "
                     "ON i.id=a.invoice_id WHERE a.payment_id=?", (payment_id,))
    co = books.company()
    receipt = p["kind"] == "receipt"
    title = "RECEIPT" if receipt else "PAYMENT VOUCHER"
    rows = "".join(f"<tr><td>{_e(a['number'])}</td><td class='r'>{_m(a['total'])}</td>"
                   f"<td class='r'>{_m(a['amount'])}</td><td class='r'>{_m(a['total'] - a['amount_paid'])}</td></tr>"
                   for a in allocs)
    part = any(a["total"] - a["amount_paid"] > 0.005 for a in allocs)
    wht = p["wht"] or 0
    body = _header(co, title + (" (PART PAYMENT)" if part else ""), f"No. {_e(p['number'])}<br>Date {p['date']}")
    body += (f"<p><b>{'Received from' if receipt else 'Paid to'}:</b> {_e(p['contact'])}<br>"
             f"<b>Amount {'received' if receipt else 'paid'}:</b> {_e(co['currency'])} {_m(p['amount'])}<br>")
    if wht:
        body += (f"<b>Withholding tax {'withheld by customer' if receipt else 'deducted'}:</b> {_m(wht)}<br>"
                 f"<b>Total settled:</b> {_m(p['amount'] + wht)}<br>")
    body += (f"<b>Method:</b> {_e(p['method'])} ({_e(p['account'])}) {_e(p['reference'])}</p>"
             f"<table><tr><th>Invoice</th><th class='r'>Invoice total</th><th class='r'>Applied now</th>"
             f"<th class='r'>Balance still due</th></tr>{rows}</table>")
    if receipt:
        body += _bank_block(co)
    body += "<p style='margin-top:50px'>Signature: ______________________</p>"
    return _open(f"{title} {p['number']}", body)


def print_statement(books, contact_id, start, end):
    st, co = books.customer_statement(contact_id, start, end), books.company()
    c = st["contact"]
    rows = "".join(f"<tr><td>{r['date']}</td><td>{_e(r['ref'])}</td><td>{r['type']}</td>"
                   f"<td class='r'>{_m(r['amount'])}</td><td class='r'>{_m(r['balance'])}</td></tr>" for r in st["rows"])
    body = _header(co, "STATEMENT", f"{start} to {end}")
    body += (f"<div class='grid'><div><b>{_e(c['name'])}</b><br><span class='muted'>{_e(c['address'])} "
             f"{_e(c['phone'])}</span></div></div><table><tr><th>Date</th><th>Reference</th><th>Type</th>"
             f"<th class='r'>Amount</th><th class='r'>Balance</th></tr><tr><td></td><td></td><td>Opening balance</td>"
             f"<td></td><td class='r'>{_m(st['opening'])}</td></tr>{rows}<tr class='tot'><td colspan=4 class='r'>"
             f"Balance due</td><td class='r'>{_m(st['closing'])}</td></tr></table>")
    if c["kind"] == "customer":
        body += _bank_block(co)
    return _open(f"STATEMENT {c['name']}", body)


def print_report(books, title, subtitle, headers, rows, money_cols=()):
    """rows: list of lists; a row may be ('__section__', text) or ('__total__', [...])."""
    co = books.company()
    mc = set(money_cols)
    th = "".join(f"<th class='{'r' if i in mc else ''}'>{_e(h)}</th>" for i, h in enumerate(headers))
    out = []
    for r in rows:
        cls = ""
        if r and r[0] == "__section__":
            out.append(f"<tr class='sec'><td colspan={len(headers)}>{_e(r[1])}</td></tr>")
            continue
        if r and r[0] == "__total__":
            cls, r = "tot", r[1]
        cells = "".join(f"<td class='{'r' if i in mc else ''}'>{_m(v) if i in mc and isinstance(v, (int, float)) else _e(v)}</td>"
                        for i, v in enumerate(r))
        out.append(f"<tr class='{cls}'>{cells}</tr>")
    body = _header(co, title, _e(subtitle)) + f"<table><tr>{th}</tr>{''.join(out)}</table>"
    return _open(f"{title} {subtitle}", body)
