"""Printable documents. Each is rendered as HTML and opened in the browser,
where the user prints or saves as PDF (no printer drivers needed in the app)."""
import html
import tempfile
import webbrowser
from pathlib import Path

from . import config as C

CSS = f"""
body{{font-family:'Space Grotesk','Segoe UI',Arial,sans-serif;color:{C.NAVY};margin:32px;font-size:13px}}
.hdr{{display:flex;justify-content:space-between;border-bottom:3px solid {C.EMERALD};padding-bottom:14px}}
h1{{margin:0;font-size:22px}} h2{{margin:0;color:{C.EMERALD};font-size:26px;text-align:right}}
.muted{{color:{C.MUTED}}} table{{width:100%;border-collapse:collapse;margin-top:18px}}
th{{background:{C.NAVY};color:#fff;text-align:left;padding:7px 8px;font-size:11px;text-transform:uppercase}}
td{{padding:7px 8px;border-bottom:1px solid {C.LINE}}} .r{{text-align:right}}
tr.tot td{{font-weight:bold;border-top:2px solid {C.NAVY}}} tr.sec td{{background:#EEF3F7;font-weight:bold}}
.grid{{display:flex;justify-content:space-between;margin-top:18px}}
.foot{{margin-top:36px;font-size:11px;color:{C.MUTED};text-align:center}}
@media print{{body{{margin:12mm}}}}
"""



def _m(v):
    v = float(v or 0)
    return f"({abs(v):,.2f})" if v < -0.004 else f"{v:,.2f}"


def _e(s):
    return html.escape(str(s or ""))


def _open(title, body):
    doc = f"<!doctype html><html><head><meta charset='utf-8'><title>{_e(title)}</title><style>{CSS}{EXTRA_CSS}</style>" \
          f"</head><body>{body}<div class='foot'>Generated by {C.APP_NAME} v{C.VERSION} \u00b7 {C.VENDOR}</div>" \
          f"<script>window.onload=()=>setTimeout(()=>window.print(),300)</script></body></html>"
    path = Path(tempfile.gettempdir()) / f"nolima_{abs(hash(title))}.html"
    path.write_text(doc, encoding="utf-8")
    webbrowser.open(path.as_uri())
    return path


def _header(company, title, subtitle=""):
    return (f"<div class='hdr'><div><h1>{_e(company['company_name'])}</h1>"
            f"<div class='muted'>{_e(company['address'])}<br>{_e(company['phone'])} {_e(company['email'])}"
            f"{'<br>TPIN: ' + _e(company['tpin']) if company.get('tpin') else ''}</div></div>"
            f"<div><h2>{_e(title)}</h2><div class='muted' style='text-align:right'>{subtitle}</div></div></div>")


def _bank_block(books):
    """All bank accounts (up to three) and mobile money, printed on every customer document."""
    banks = [b for b in books.banks() if b["name"].strip() or b["account_no"].strip()]
    mm = (books.setting("mobile_money", "") or "").strip()
    if not banks and not mm:
        return ""
    cols = ""
    for b in banks:
        cols += ("<td class='bcol'>"
                 f"<div class='bname'>{_e(b['name'])}</div>"
                 + (f"<div><span class='muted'>Branch:</span> {_e(b['branch'])}</div>" if b["branch"] else "")
                 + (f"<div><span class='muted'>Account name:</span> {_e(b['account_name'])}</div>"
                    if b["account_name"] else "")
                 + (f"<div><span class='muted'>Account no.:</span> <b>{_e(b['account_no'])}</b></div>"
                    if b["account_no"] else "")
                 + "</td>")
    out = "<div class='bank'><div class='bt'>PAYMENT DETAILS</div>"
    if cols:
        out += f"<table class='bktab'><tr>{cols}</tr></table>"
    if mm:
        out += f"<div class='mm'><span class='muted'>Mobile money:</span> <b>{_e(mm)}</b></div>"
    return out + "</div>"


def _lines_table(co, lines, doc):
    has_disc = any((l["discount_pct"] or 0) for l in lines)
    head = ("<tr><th>Description</th><th class='r'>Qty</th><th class='r'>Unit price</th>"
            + ("<th class='r'>Disc.</th>" if has_disc else "")
            + f"<th class='r'>VAT</th><th class='r'>Amount ({_e(co['currency'])})</th></tr>")
    body = ""
    for l in lines:
        body += (f"<tr><td>{_e(l['description'])}</td><td class='r'>{l['qty']:g}</td>"
                 f"<td class='r'>{_m(l['unit_price'])}</td>"
                 + (f"<td class='r'>{(l['discount_pct'] or 0):g}%</td>" if has_disc else "")
                 + f"<td class='r'>{l['vat_rate']:g}%</td><td class='r'>{_m(l['net'])}</td></tr>")
    span = 5 if has_disc else 4
    tot = ""
    if doc["discount"]:
        tot += f"<tr><td colspan={span} class='r muted'>Discount given</td><td class='r muted'>({_m(doc['discount'])})</td></tr>"
    tot += f"<tr><td colspan={span} class='r'>Subtotal</td><td class='r'>{_m(doc['subtotal'])}</td></tr>"
    tot += f"<tr><td colspan={span} class='r'>VAT</td><td class='r'>{_m(doc['vat'])}</td></tr>"
    if doc["levy"]:
        tot += (f"<tr><td colspan={span} class='r'>Tourism levy ({float(co['tourism_levy_rate'] or 0):g}%)</td>"
                f"<td class='r'>{_m(doc['levy'])}</td></tr>")
    tot += f"<tr class='tot'><td colspan={span} class='r'>Total</td><td class='r'>{_m(doc['total'])}</td></tr>"
    return f"<table>{head}{body}{tot}", span


EXTRA_CSS = f"""
.bank{{margin-top:22px;border:1px solid {C.LINE};border-radius:10px;padding:12px 14px;background:#F6FAF8}}
.bt{{font-size:11px;font-weight:bold;color:{C.EMERALD};letter-spacing:.5px;margin-bottom:6px}}
.bktab{{margin-top:0;width:100%}} .bktab td{{border:none;padding:4px 18px 4px 0;vertical-align:top;line-height:1.55}} .bname{{font-weight:bold;color:#0F2A47;margin-bottom:2px}} .mm{{margin-top:6px;padding-top:6px;border-top:1px dashed #DCE3EA}} .stamp{{display:inline-block;padding:3px 10px;border-radius:12px;
font-size:11px;font-weight:bold}} .paid{{background:#DCFCE7;color:#166534}} .partial{{background:#FEF3C7;color:#92400E}}
.open{{background:#E0E7FF;color:#3730A3}} .void{{background:#FEE2E2;color:#991B1B}}
"""


DOC_CSS = """
body{font-family:Helvetica,Arial,sans-serif;color:#111;margin:34px 40px;font-size:13px}
.top{display:table;width:100%} .top>div{display:table-cell;vertical-align:top}
.co{width:38%} .co b{font-size:15px} .ttl{text-align:center;font-size:24px;font-weight:600;padding-top:2px}
.logo{text-align:right;width:30%} .logo img{max-height:70px;max-width:180px}
hr.rule{border:0;border-top:2px solid #111;margin:28px 0 6px}
.mid{display:table;width:100%} .mid>div{display:table-cell;vertical-align:top}
.addr{width:50%;line-height:1.55} .addr .lbl{font-size:11px;font-weight:bold;text-decoration:underline}
.boxes{border-collapse:collapse;float:right;border-bottom:1px solid #111} .boxes td{padding:12px 22px;
text-align:center;font-size:14px;line-height:1.5;width:120px} .boxes .g{background:#D0D0D0} .boxes .k{background:#000;
color:#fff} .boxes .k b{font-size:14px}
table.ln{width:100%;border-collapse:collapse;margin-top:58px} table.ln th{font-size:11px;text-align:left;padding:8px 4px;
border-top:1px solid #bbb;border-bottom:1px solid #bbb} table.ln td{padding:6px 4px;vertical-align:top}
table.ln tr.last td{border-bottom:1px solid #bbb} .r{text-align:right} .c{text-align:center} table.ln th.r,table.ts th.r{text-align:right}
.tot{width:48%;margin-left:52%;border-collapse:collapse} .tot td{padding:3px 4px} .tot .big td{border-top:1px solid #bbb;
border-bottom:1px solid #111;padding:14px 4px;font-size:15px} .tot .big td.v{font-size:22px}
.thanks{text-align:right;margin:10px 0 24px}
.tsh{font-size:15px;margin-bottom:6px} table.ts{width:100%;border-collapse:collapse} table.ts th{font-size:11px;
border-top:1px solid #bbb;border-bottom:1px solid #bbb;padding:7px 4px} table.ts td{padding:6px 4px}
table.ts tr:last-child td{border-bottom:1px solid #bbb}
.bank{margin-top:22px;border:1px solid #ccc;border-radius:6px;padding:10px 14px} .bt{font-size:11px;font-weight:bold;
margin-bottom:4px} .bktab{width:100%;border-collapse:collapse} .bktab td{border:none;padding:3px 18px 3px 0;
vertical-align:top;line-height:1.5} .bname{font-weight:bold} .mm{margin-top:6px;padding-top:6px;border-top:1px dashed #ccc}
.muted{color:#555} .note{margin-top:14px;color:#333}
.accept{display:table;width:100%;margin-top:40px} .accept>div{display:table-cell;width:50%;padding-right:30px}
.accept .line{border-top:1px solid #111;padding-top:4px;margin-top:34px;font-size:12px}
.foot{margin-top:46px;text-align:center;font-size:11px;line-height:1.5}
@media print{body{margin:12mm 14mm}}
"""


def _d(iso):
    """2026-09-16 -> 16/09/2026 (dates on documents are day/month/year)."""
    try:
        y, m, dd = str(iso).split("-")
        return f"{dd}/{m}/{y}"
    except ValueError:
        return _e(iso)


def _logo(books):
    b64 = books.setting("logo_png", "") or ""
    return f"<img src='data:image/png;base64,{b64}'>" if b64 else ""


def _tax_rows(books, lines, doc):
    """Tax summary: tourism levy and VAT together, each with the net it was calculated on."""
    co = books.company()
    rows = []
    if doc["levy"]:
        rows.append((f"Ministry of Tourism @ {float(co['tourism_levy_rate'] or 0):g}%", doc["levy"], doc["subtotal"]))
    rates = sorted({l["vat_rate"] for l in lines if l["vat_rate"]})
    for rate in rates:
        net = sum(l["net"] for l in lines if l["vat_rate"] == rate)
        vat = sum(l["vat"] for l in lines if l["vat_rate"] == rate)
        rows.append((f"Malawi Revenue Authority @ {rate:g}%", vat, net))
    return rows


def _document(books, kind, doc, lines, extra_totals="", after="", accept=False):
    """Shared layout for invoices and quotations (modelled on the lodge's own quotation)."""
    co = books.company()
    number = doc["number"]
    title = {"quote": "Quote", "sale": "Invoice", "bill": "Supplier bill"}[kind]
    third_label, third = ("EXPIRATION<br>DATE", doc["valid_until"]) if kind == "quote" else \
        ("DUE<br>DATE", doc["due_date"])
    big_label, big = ("TOTAL", doc["total"])
    if kind != "quote" and (doc["amount_paid"] or 0) > 0.004 and doc["status"] != "void":
        big_label, big = ("BALANCE DUE", doc["total"] - doc["amount_paid"])
    addr = "<br>".join(_e(x) for x in [doc["contact"]] + (doc["address"] or "").splitlines() if x)
    has_disc = any((l["discount_pct"] or 0) for l in lines)
    has_date = any((l["line_date"] or "") for l in lines)
    head = ("<tr>" + ("<th>DATE</th>" if has_date else "") + "<th>DESCRIPTION</th><th class='r'>QTY</th>"
            "<th class='r'>RATE</th>" + ("<th class='r'>DISC.</th>" if has_disc else "") +
            "<th class='r'>AMOUNT</th></tr>")
    body = ""
    for i, l in enumerate(lines):
        cls = " class='last'" if i == len(lines) - 1 else ""
        body += (f"<tr{cls}>" + (f"<td>{_e(l['line_date'])}</td>" if has_date else "") +
                 f"<td>{_e(l['description'])}</td><td class='r'>{l['qty']:g}</td><td class='r'>{_m(l['unit_price'])}</td>"
                 + (f"<td class='r'>{(l['discount_pct'] or 0):g}%</td>" if has_disc else "") +
                 f"<td class='r'>{_m(l['net'])}</td></tr>")
    tax = (doc["vat"] or 0) + (doc["levy"] or 0)
    tot = ""
    if doc["discount"]:
        tot += f"<tr><td>DISCOUNT</td><td class='r'>({_m(doc['discount'])})</td></tr>"
    tot += (f"<tr><td>SUBTOTAL</td><td class='r'>{_m(doc['subtotal'])}</td></tr>"
            f"<tr><td>TAX</td><td class='r'>{_m(tax)}</td></tr>" + extra_totals +
            f"<tr class='big'><td>{'BALANCE DUE' if big_label == 'BALANCE DUE' else 'TOTAL'}</td>"
            f"<td class='r v'>MK{_m(big)}</td></tr>")
    ts = _tax_rows(books, lines, doc)
    tax_html = ""
    if ts:
        tax_html = ("<div class='tsh'>TAX SUMMARY</div><table class='ts'><tr><th class='r' style='width:40%'>RATE</th>"
                    "<th class='r'>TAX</th><th class='r'>NET</th></tr>" +
                    "".join(f"<tr><td class='r'>{_e(n)}</td><td class='r'>{_m(t)}</td><td class='r'>{_m(net)}</td></tr>"
                            for n, t, net in ts) + "</table>")
    foot_bits = [x for x in ["Address| " + " ".join((co["address"] or "").split()) if co["address"] else "",
                             "Cell:" + co["phone"] if co["phone"] else ""] if x]
    foot = (f"<div class='foot'>{_e(co['company_name'])}<br>{_e(' | '.join(foot_bits))}"
            + (f"<br>Email: {_e(co['email'])}" if co["email"] else "") + "</div>")
    html = (f"<div class='top'><div class='co'><b>{_e(co['company_name'])}</b><br><br>{_e(co['email'])}"
            + (f"<br>VAT Registration No. {_e(co['tpin'])}" if co["tpin"] else "") + "</div>"
            f"<div class='ttl'>{title}&nbsp; {_e(number)}</div><div class='logo'>{_logo(books)}</div></div>"
            f"<hr class='rule'><div class='mid'><div class='addr'><span class='lbl'>"
            f"{'SUPPLIER' if kind == 'bill' else 'ADDRESS'}</span><br>{addr}"
            + (f"<br><span class='muted'>Ref: {_e(doc['reference'])}</span>" if doc["reference"] else "") + "</div>"
            f"<div><table class='boxes'><tr><td class='g'>DATE<br>{_d(doc['date'])}</td>"
            f"<td class='k'>{big_label}<br><b>MK{_m(big)}</b></td><td class='g'>{third_label}<br>{_d(third)}</td>"
            f"</tr></table></div></div>"
            f"<table class='ln'>{head}{body}</table><table class='tot'>{tot}</table>"
            f"<div class='thanks'>THANK YOU.</div>{tax_html}{after}")
    if doc["memo"]:
        html += f"<div class='note'>{_e(doc['memo'])}</div>"
    if kind != "bill":
        html += _bank_block(books)
    if accept:
        html += ("<div class='accept'><div><div class='line'>Accepted By</div></div>"
                 "<div><div class='line'>Accepted Date</div></div></div>")
    html += foot
    page = (f"<!doctype html><html><head><meta charset='utf-8'><title>{title} {_e(number)}</title>"
            f"<style>{DOC_CSS}</style></head><body>{html}"
            f"<script>window.onload=()=>setTimeout(()=>window.print(),300)</script></body></html>")
    path = Path(tempfile.gettempdir()) / f"nolima_{kind}_{number}.html".replace("/", "-")
    path.write_text(page, encoding="utf-8")
    webbrowser.open(path.as_uri())
    return path


def print_invoice(books, inv_id):
    inv, lines = books.invoice(inv_id), books.invoice_lines(inv_id)
    extra = ""
    wht = inv["wht"] or 0
    paid = (inv["amount_paid"] or 0) - wht
    if inv["status"] != "void" and (wht or paid > 0.004):
        extra += f"<tr><td>TOTAL</td><td class='r'>{_m(inv['total'])}</td></tr>"
        if wht:
            extra += f"<tr><td>LESS WITHHOLDING TAX</td><td class='r'>({_m(wht)})</td></tr>"
        if paid > 0.004:
            extra += f"<tr><td>PAID</td><td class='r'>({_m(paid)})</td></tr>"
    after = ""
    if inv["status"] == "void":
        after = "<div class='note'><b>VOID</b> - this invoice has been cancelled.</div>"
    elif inv["kind"] == "sale" and inv["status"] != "paid" and books.setting("payment_terms", ""):
        after = f"<div class='note muted'>{_e(books.setting('payment_terms', ''))}</div>"
    return _document(books, inv["kind"], inv, lines, extra, after)


def print_quote(books, qid):
    q, lines = books.quote(qid), books.quote_lines(qid)
    return _document(books, "quote", q, lines, accept=True)


def print_payment(books, payment_id):
    p = books.one("SELECT p.*, c.name AS contact, a.name AS account FROM payments p JOIN contacts c ON "
                  "c.id=p.contact_id JOIN accounts a ON a.id=p.account_id WHERE p.id=?", (payment_id,))
    allocs = books.q("SELECT i.number, i.total, i.amount_paid, a.amount FROM allocations a JOIN invoices i "
                     "ON i.id=a.invoice_id WHERE a.payment_id=?", (payment_id,))
    co = books.company()
    receipt = p["kind"] == "receipt"
    title = "RECEIPT" if receipt else "PAYMENT VOUCHER"
    rows = "".join(f"<tr><td>{_e(a['number'])}</td><td class='r'>{_m(a['total'])}</td>"
                   f"<td class='r'>{_m(a['amount'])}</td><td class='r'>{_m(a['total'] - a['amount_paid'])}</td></tr>"
                   for a in allocs)
    part = any(a["total"] - a["amount_paid"] > 0.005 for a in allocs)
    wht = p["wht"] or 0
    body = _header(co, title + (" (PART PAYMENT)" if part else ""), f"No. {_e(p['number'])}<br>Date {p['date']}")
    body += (f"<p><b>{'Received from' if receipt else 'Paid to'}:</b> {_e(p['contact'])}<br>"
             f"<b>Amount {'received' if receipt else 'paid'}:</b> {_e(co['currency'])} {_m(p['amount'])}<br>")
    if wht:
        body += (f"<b>Withholding tax {'withheld by customer' if receipt else 'deducted'}:</b> {_m(wht)}<br>"
                 f"<b>Total settled:</b> {_m(p['amount'] + wht)}<br>")
    body += (f"<b>Method:</b> {_e(p['method'])} ({_e(p['account'])}) {_e(p['reference'])}</p>"
             f"<table><tr><th>Invoice</th><th class='r'>Invoice total</th><th class='r'>Applied now</th>"
             f"<th class='r'>Balance still due</th></tr>{rows}</table>")
    if receipt:
        body += _bank_block(books)
    body += "<p style='margin-top:50px'>Signature: ______________________</p>"
    return _open(f"{title} {p['number']}", body)


def print_statement(books, contact_id, start, end):
    st, co = books.customer_statement(contact_id, start, end), books.company()
    c = st["contact"]
    rows = "".join(f"<tr><td>{r['date']}</td><td>{_e(r['ref'])}</td><td>{r['type']}</td>"
                   f"<td class='r'>{_m(r['amount'])}</td><td class='r'>{_m(r['balance'])}</td></tr>" for r in st["rows"])
    body = _header(co, "STATEMENT", f"{start} to {end}")
    body += (f"<div class='grid'><div><b>{_e(c['name'])}</b><br><span class='muted'>{_e(c['address'])} "
             f"{_e(c['phone'])}</span></div></div><table><tr><th>Date</th><th>Reference</th><th>Type</th>"
             f"<th class='r'>Amount</th><th class='r'>Balance</th></tr><tr><td></td><td></td><td>Opening balance</td>"
             f"<td></td><td class='r'>{_m(st['opening'])}</td></tr>{rows}<tr class='tot'><td colspan=4 class='r'>"
             f"Balance due</td><td class='r'>{_m(st['closing'])}</td></tr></table>")
    if c["kind"] == "customer":
        body += _bank_block(books)
    return _open(f"STATEMENT {c['name']}", body)


def print_report(books, title, subtitle, headers, rows, money_cols=()):
    """rows: list of lists; a row may be ('__section__', text) or ('__total__', [...])."""
    co = books.company()
    mc = set(money_cols)
    th = "".join(f"<th class='{'r' if i in mc else ''}'>{_e(h)}</th>" for i, h in enumerate(headers))
    out = []
    for r in rows:
        cls = ""
        if r and r[0] == "__section__":
            out.append(f"<tr class='sec'><td colspan={len(headers)}>{_e(r[1])}</td></tr>")
            continue
        if r and r[0] == "__total__":
            cls, r = "tot", r[1]
        cells = "".join(f"<td class='{'r' if i in mc else ''}'>{_m(v) if i in mc and isinstance(v, (int, float)) else _e(v)}</td>"
                        for i, v in enumerate(r))
        out.append(f"<tr class='{cls}'>{cells}</tr>")
    body = _header(co, title, _e(subtitle)) + f"<table><tr>{th}</tr>{''.join(out)}</table>"
    return _open(f"{title} {subtitle}", body)
