"""Printable documents. Each is rendered as HTML and opened in the browser,
where the user prints or saves as PDF (no printer drivers needed in the app)."""
import html
import tempfile
import webbrowser
from pathlib import Path

from . import config as C

CSS = f"""
body{{font-family:'Space Grotesk','Segoe UI',Arial,sans-serif;color:{C.NAVY};margin:32px;font-size:13px}}
.hdr{{display:flex;justify-content:space-between;border-bottom:3px solid {C.EMERALD};padding-bottom:14px}}
h1{{margin:0;font-size:22px}} h2{{margin:0;color:{C.EMERALD};font-size:26px;text-align:right}}
.muted{{color:{C.MUTED}}} table{{width:100%;border-collapse:collapse;margin-top:18px}}
th{{background:{C.NAVY};color:#fff;text-align:left;padding:7px 8px;font-size:11px;text-transform:uppercase}}
td{{padding:7px 8px;border-bottom:1px solid {C.LINE}}} .r{{text-align:right}}
tr.tot td{{font-weight:bold;border-top:2px solid {C.NAVY}}} tr.sec td{{background:#EEF3F7;font-weight:bold}}
.grid{{display:flex;justify-content:space-between;margin-top:18px}}
.foot{{margin-top:36px;font-size:11px;color:{C.MUTED};text-align:center}}
@media print{{body{{margin:12mm}}}}
"""


def _m(v):
    v = float(v or 0)
    return f"({abs(v):,.2f})" if v < -0.004 else f"{v:,.2f}"


def _e(s):
    return html.escape(str(s or ""))


def _open(title, body):
    doc = f"<!doctype html><html><head><meta charset='utf-8'><title>{_e(title)}</title><style>{CSS}</style>" \
          f"</head><body>{body}<div class='foot'>Generated by {C.APP_NAME} v{C.VERSION} \u00b7 {C.VENDOR}</div>" \
          f"<script>window.onload=()=>setTimeout(()=>window.print(),300)</script></body></html>"
    path = Path(tempfile.gettempdir()) / f"nolima_{abs(hash(title))}.html"
    path.write_text(doc, encoding="utf-8")
    webbrowser.open(path.as_uri())
    return path


def _header(company, title, subtitle=""):
    return (f"<div class='hdr'><div><h1>{_e(company['company_name'])}</h1>"
            f"<div class='muted'>{_e(company['address'])}<br>{_e(company['phone'])} {_e(company['email'])}"
            f"{'<br>TPIN: ' + _e(company['tpin']) if company.get('tpin') else ''}</div></div>"
            f"<div><h2>{_e(title)}</h2><div class='muted' style='text-align:right'>{subtitle}</div></div></div>")


def print_invoice(books, inv_id):
    inv, lines, co = books.invoice(inv_id), books.invoice_lines(inv_id), books.company()
    title = "TAX INVOICE" if inv["kind"] == "sale" else "SUPPLIER BILL"
    if inv["status"] == "paid" and inv["kind"] == "sale" and inv["date"] == inv["due_date"]:
        title = "CASH SALE RECEIPT"
    rows = "".join(f"<tr><td>{_e(l['description'])}</td><td class='r'>{l['qty']:g}</td>"
                   f"<td class='r'>{_m(l['unit_price'])}</td><td class='r'>{l['vat_rate']:g}%</td>"
                   f"<td class='r'>{_m(l['net'])}</td></tr>" for l in lines)
    body = _header(co, title, f"No. {_e(inv['number'])}<br>Date {inv['date']}<br>Due {inv['due_date']}")
    body += (f"<div class='grid'><div><b>{'Bill to' if inv['kind'] == 'sale' else 'Supplier'}</b><br>"
             f"{_e(inv['contact'])}<br><span class='muted'>{_e(inv['address'])} {_e(inv['phone'])}</span></div>"
             f"<div class='muted'>{'Status: ' + inv['status'].upper()}</div></div>"
             f"<table><tr><th>Description</th><th class='r'>Qty</th><th class='r'>Unit price</th>"
             f"<th class='r'>VAT</th><th class='r'>Amount ({_e(co['currency'])})</th></tr>{rows}"
             f"<tr><td colspan=4 class='r'>Subtotal</td><td class='r'>{_m(inv['subtotal'])}</td></tr>"
             f"<tr><td colspan=4 class='r'>VAT</td><td class='r'>{_m(inv['vat'])}</td></tr>"
             f"<tr class='tot'><td colspan=4 class='r'>Total</td><td class='r'>{_m(inv['total'])}</td></tr>"
             f"<tr><td colspan=4 class='r'>Paid</td><td class='r'>{_m(inv['amount_paid'])}</td></tr>"
             f"<tr class='tot'><td colspan=4 class='r'>Balance due</td>"
             f"<td class='r'>{_m(inv['total'] - inv['amount_paid'])}</td></tr></table>")
    if inv["memo"]:
        body += f"<p class='muted'>{_e(inv['memo'])}</p>"
    return _open(f"{title} {inv['number']}", body)


def print_payment(books, payment_id):
    p = books.one("SELECT p.*, c.name AS contact, a.name AS account FROM payments p JOIN contacts c ON "
                  "c.id=p.contact_id JOIN accounts a ON a.id=p.account_id WHERE p.id=?", (payment_id,))
    allocs = books.q("SELECT i.number, a.amount FROM allocations a JOIN invoices i ON i.id=a.invoice_id "
                     "WHERE a.payment_id=?", (payment_id,))
    co = books.company()
    title = "RECEIPT" if p["kind"] == "receipt" else "PAYMENT VOUCHER"
    rows = "".join(f"<tr><td>{_e(a['number'])}</td><td class='r'>{_m(a['amount'])}</td></tr>" for a in allocs)
    body = _header(co, title, f"No. {_e(p['number'])}<br>Date {p['date']}")
    body += (f"<p><b>{'Received from' if p['kind'] == 'receipt' else 'Paid to'}:</b> {_e(p['contact'])}<br>"
             f"<b>Amount:</b> {_e(co['currency'])} {_m(p['amount'])}<br><b>Method:</b> {_e(p['method'])} "
             f"({_e(p['account'])}) {_e(p['reference'])}</p>"
             f"<table><tr><th>Applied to</th><th class='r'>Amount</th></tr>{rows}</table>"
             f"<p style='margin-top:50px'>Signature: ______________________</p>")
    return _open(f"{title} {p['number']}", body)


def print_report(books, title, subtitle, headers, rows, money_cols=()):
    """rows: list of lists; a row may be ('__section__', text) or ('__total__', [...])."""
    co = books.company()
    mc = set(money_cols)
    th = "".join(f"<th class='{'r' if i in mc else ''}'>{_e(h)}</th>" for i, h in enumerate(headers))
    out = []
    for r in rows:
        cls = ""
        if r and r[0] == "__section__":
            out.append(f"<tr class='sec'><td colspan={len(headers)}>{_e(r[1])}</td></tr>")
            continue
        if r and r[0] == "__total__":
            cls, r = "tot", r[1]
        cells = "".join(f"<td class='{'r' if i in mc else ''}'>{_m(v) if i in mc and isinstance(v, (int, float)) else _e(v)}</td>"
                        for i, v in enumerate(r))
        out.append(f"<tr class='{cls}'>{cells}</tr>")
    body = _header(co, title, _e(subtitle)) + f"<table><tr>{th}</tr>{''.join(out)}</table>"
    return _open(f"{title} {subtitle}", body)
